services:
  db:
    image: 'postgres:15.2-alpine'
    environment:
      POSTGRES_DB: access_issues
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data