export const summersvilleRoutes = [
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Unnamed',
    Grade: '5.7',
    Type: 'Trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'no',
    Stars: 1,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Armada',
    Grade: '12d',
    Type: 'Sport',
    Bolts: '7',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'The Skull in the Stone',
    Grade: '12c',
    Type: 'Sport',
    Bolts: '7',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Walk the Plank',
    Grade: '11b',
    Type: 'Sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Man Overboard',
    Grade: '11d',
    Type: 'Sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Mutiny',
    Grade: '11d',
    Type: 'Sport',
    Bolts: '6',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Unnamed',
    Grade: '10',
    Type: 'Trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Power Bait',
    Grade: '14a',
    Type: 'Sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Black Panther',
    Grade: '13a',
    Type: 'Sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Unnamed',
    Grade: '9',
    Type: 'Trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'no',
    Stars: 1,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Unnamed',
    Grade: '10b',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'no',
    Stars: 1,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Unnamed',
    Grade: '9',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: '1 bolt ancor',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Indian Summer',
    Grade: '10c',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: '1 bolt ancor',
    Stars: 3,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Unnamed',
    Grade: '10a',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'no',
    Stars: 1,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Another Name for Pirate Treasure',
    Grade: '11d',
    Type: 'Sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Unnamed',
    Grade: '10a',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'no',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Spanmoth Armada ',
    Grade: '',
    Type: '',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: '',
    Stars: null,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'The Good, the Bad and the Boltless',
    Grade: '10',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: "Pirate's Cove ",
    Route: 'Vertical Plains Drifter',
    Grade: '10',
    Type: 'trad',
    Bolts: '2',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Reckless Abandon',
    Grade: '12a',
    Type: 'sport',
    Bolts: '6',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Surfer Rosa',
    Grade: '12d',
    Type: 'sport',
    Bolts: '7',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Obitchuary',
    Grade: '12b',
    Type: 'sport',
    Bolts: '9',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Tobacco Road',
    Grade: '12b',
    Type: 'sport',
    Bolts: '7',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Mercy Seat',
    Grade: '13a',
    Type: 'sport',
    Bolts: '9',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Apollo Reed',
    Grade: '13a',
    Type: 'sport',
    Bolts: '11',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Journeyman',
    Grade: '14a',
    Type: 'sport',
    Bolts: '11',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'B.C.',
    Grade: '13 b/c',
    Type: 'sport',
    Bolts: '11',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Pod',
    Grade: '13b',
    Type: 'sport',
    Bolts: '9',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Super Pod',
    Grade: '14d',
    Type: 'Sport',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: null,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Full Metal Brisket',
    Grade: '15a',
    Type: 'Sport',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: '',
    Stars: null,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Prohibition',
    Grade: '',
    Type: '',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: '',
    Stars: null,
  },
  {
    Area: 'Summersville ',
    Wall: 'Coliseum',
    Route: 'Still Life',
    Grade: '14b',
    Type: 'sport',
    Bolts: '8',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'Sudetic Verticalia',
    Grade: '10a',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'Do it ',
    Grade: '11a',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'Trigger Happy',
    Grade: '10a',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: "Stick 'em up ",
    Grade: '10b',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'Gun Lust',
    Grade: '10c',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'Armed and Dangerous',
    Grade: '10b',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'Gunned but not forgotten',
    Grade: '10d',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'In the Line of Fire',
    Grade: '10d',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'Gun Wall ',
    Route: 'The Surpus',
    Grade: '10c',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: 'Summersville ',
    Wall: 'D.C. Memorial Boulder',
    Route: "Quarrymen's Hands",
    Grade: '12a',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Power Outage',
    Grade: '12d',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Euro Dude',
    Grade: '11a',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Maia Not Mia',
    Grade: '10a',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: "Showercam, and Your Wife's the Star",
    Grade: '5.9',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Hillbilly Golf=White Gas, Beer Can and a Golf Club',
    Grade: '5.6',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Unnamed',
    Grade: '10b',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 0,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Spyder Needs a Thesaurus',
    Grade: '12a',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Angle of Attack',
    Grade: '12c',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Animal Logic',
    Grade: '12b',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Project',
    Grade: '',
    Type: '',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: '',
    Stars: null,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Skinny Legs',
    Grade: '13b',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Pro-Vision',
    Grade: '13a',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Straight and Narrow',
    Grade: '11b',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Process of Elimination',
    Grade: '11a',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'The Route of All Evil',
    Grade: '11b',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: 'D.C. Memorial Boulder',
    Route: 'Psycho Babble',
    Grade: '12a',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: '**Check updated books for change at this area',
    Route: '',
    Grade: '',
    Type: '',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: '',
    Stars: null,
  },
  {
    Area: '',
    Wall: 'Long Wall ',
    Route: 'Rocky Top Hilton',
    Grade: '10a',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Seven Minutes of Heaven',
    Grade: '11d',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: '',
    Route: 'On the Porch',
    Grade: '5.9',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 1,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Ragged Reaction',
    Grade: '5.9',
    Type: 'sport',
    Bolts: '3',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Chewy',
    Grade: '10b',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Menace Alert',
    Grade: '5.9',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Going Ballistic',
    Grade: '10d',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Flight Path',
    Grade: '10b',
    Type: 'sport',
    Bolts: '4',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Hot and Bothered',
    Grade: '11d',
    Type: 'sport',
    Bolts: '6',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Under the Milky Way',
    Grade: '11d',
    Type: 'sport',
    Bolts: '7',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 4,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Flirting with E',
    Grade: '11d',
    Type: 'sport',
    Bolts: '6',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Maximum Overdrive',
    Grade: '11c',
    Type: 'sport',
    Bolts: '7',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 3,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Cave Woman ',
    Grade: '10d',
    Type: 'trad',
    Bolts: '',
    Pins: '',
    is2BoltAnchor: 'no',
    Stars: 1,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Fifty-Fifty',
    Grade: '11a',
    Type: 'sport',
    Bolts: '7',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Minimum Overdrive',
    Grade: '11a',
    Type: 'sport',
    Bolts: '6',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Spice',
    Grade: '11b',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Gimme Some Tongue',
    Grade: '11c',
    Type: 'sport',
    Bolts: '5',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: '',
    Route: 'Stone Cold Doxie',
    Grade: '11b',
    Type: 'sport',
    Bolts: '6',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
  {
    Area: '',
    Wall: '',
    Route: "No Way Jose'",
    Grade: '11b',
    Type: 'sport',
    Bolts: '6',
    Pins: '',
    is2BoltAnchor: 'yes',
    Stars: 2,
  },
]
